### ISSUE TITLE
Bigquery : magic arg ``--destination_table`` issue, with google-cloud-bigquery-magics

### ISSUE THREAD

**Issue by julioyildo** [googleapis/python-bigquery#53] opened 2020-03-06 14:13 UTC
Hi

I would like to use Bigquery's magic commands to make a query that can create and store the result in a new Bigquery table.

I'm trying to use the following method : 
`%%bigquery   --use_legacy_sql  --project projectName  --destination_table datasetname.tablename `

But currently having this issue :
_`unrecognized arguments: --destination_table datasetname.tablename`_

This argument is mentioned in the Source code for [google.cloud.bigquery.magics.](https://googleapis.dev/python/bigquery/latest/_modules/google/cloud/bigquery/magics.html)

Thanks for your help !

**Comment by plamut** [comment] 2020-03-10 10:33
@julioyildo Which BigQuery version do you use?

I was not able to reproduce the error in `v1.24.0`. However, I did manage to get the following error if putting the tablename argument on its own line instead of having all arguments in the same line:
```
UsageError: argument --destination_table: expected one argument
```

When using the cell magic, is there any extra whitespace in the input that might have confused the parser? Or something else that differs from the command posted in the issue description?

**Comment by julioyildo** [comment] 2020-03-12 13:56
@plamut  Thank you for your help.

I upgraded to `v1.22.0` and `--destination_table`  works fine. 
However,  I still have some questions about some features that could improve the library.

**A ) Being able to enter `table_id` as we can do with `--params` for values parameters e.g.**

```%%bigquery  --project projectName --params {"InputTableId" : `<table_id>`}  --destination_table <datasetName>.<OutputTableName>``` 
```SELECT *  FROM @InputTableId```


**B ) Possibility to add a table field name as parameter e.g.**

```%%bigquery  --project projectName --params {"fieldName" : <field_name>} ``` 
``SELECT @fieldName  FROM <table_name>``

**Are these features planned for future releases ?** 

Thank you !

**Comment by julioyildo** [comment] 2020-03-12 13:59
> @julioyildo Which BigQuery version do you use?
> 
> I was not able to reproduce the error in `v1.24.0`. However, I did manage to get the following error if putting the tablename argument on its own line instead of having all arguments in the same line:
> 
> ```
> UsageError: argument --destination_table: expected one argument
> ```
> 
> When using the cell magic, is there any extra whitespace in the input that might have confused the parser? Or something else that differs from the command posted in the issue description?
> 
> **Update:** I checked the history and `--destination_table` argument has been [added in v1.22.0](https://github.com/googleapis/python-bigquery/blob/master/CHANGELOG.md#new-features-2) - upgrading the client to a more recent version should get rid of the problem.



> @julioyildo Which BigQuery version do you use?
> 
> I was not able to reproduce the error in `v1.24.0`. However, I did manage to get the following error if putting the tablename argument on its own line instead of having all arguments in the same line:
> 
> ```
> UsageError: argument --destination_table: expected one argument
> ```
> 
> When using the cell magic, is there any extra whitespace in the input that might have confused the parser? Or something else that differs from the command posted in the issue description?
> 
> **Update:** I checked the history and `--destination_table` argument has been [added in v1.22.0](https://github.com/googleapis/python-bigquery/blob/master/CHANGELOG.md#new-features-2) - upgrading the client to a more recent version should get rid of the problem.

@plamut  Thank you for your help.

I upgraded to `v1.22.0` and `--destination_table`  works fine. 
However,  I still have some questions about some features that could improve the library.

**A ) Being able to enter `table_id` as we can do with `--params` for values parameters e.g.**

```%%bigquery  --project projectName --params {"InputTableId" : `<table_id>`}  --destination_table <datasetName>.<OutputTableName>``` 
```SELECT *  FROM @InputTableId```


**B ) Possibility to add a table field name as parameter e.g.**

```%%bigquery  --project projectName --params {"fieldName" : <field_name>} ``` 
``SELECT @fieldName  FROM <table_name>``

**Are these features planned for future releases ?** 

Thank you !

**Comment by plamut** [comment] 2020-03-12 15:09
@julioyildo I will be back next week, and can give a more detailed answer then.

Good to hear that the upgrade worked! As for the table ID, you can provide it in the cell body instead of the query, and the cell magic will magically fetch the rows from that table:
```
%%bigquery --max_results 100
my-project.my-dataset.my-table-name
```

**Comment by plamut** [comment] 2020-03-16 15:13
@julioyildo Does the suggestion answer the question A for you?

As for the question B, you are correct that this is currently not possible, as mentioned in the [documentation](https://cloud.google.com/bigquery/docs/parameterized-queries#running_parameterized_queries):

> ... Parameters cannot be used as substitutes for identifiers, column names, table names, or other parts of the query.

Supporting that is outside the scope of the client library, it would have to be implemented on the backend. I can nevertheless check if a feature like this is planned in the future.

**Comment by plamut** [comment] 2020-03-17 17:27
@julioyildo I got the answer on B - parametrized identifiers, table names, etc. are not planned, but there is a plan to add the ability to execute raw queries, i.e. without any parameter escaping and other checks (something similar to EXECUTE IMMEDIATE).

That feature will allow executing any parametrized raw string, which could also include dynamic table names, for instance. However, that kind of flexibility will come at the expense of security, as users will be solely responsible for proper parameter escaping, and for the actual command string they send to the backend. There will be no safety net the current query parameters offer.

**Comment by julioyildo** [comment] 2020-03-17 19:21
@plamut first of all, I'm sorry for the response time. 
Thank you very much for all the information.

A) The answer A doesn't meet correctly our needs. Actually we need to be able to templatise notebooks that could be used with Input Table Ids and OutPut Table Ids (=e.g. --destination_table) dynamically for all our different customers. 
If the functionality isn't planned, perhaps we could propose you a pull request ?

B) Interesting, do you know when this feature could be released? 

Thank you !

**Comment by plamut** [comment] 2020-03-18 10:08
@julioyildo 
A) If I understand correctly, you would need a new magic option `--source_table` or something like that? That would not be too difficult to add, will check with the product owner. I will open a separate feature request ticket for it.

B) I don't know, sorry. If I had to guess and if it helps with your project plans, it's probably not something that will be added "soon" (say, in a month), it will likely take at least a quarter or more. Please mind that this is solely **my own opinion** and **not an official answer** in any way.

**Comment by julioyildo** [comment] 2020-03-18 14:13
@plamut 
A) Yes exactly! :) 

B) All right, thanks.

**Comment by plamut** [comment] 2020-03-24 13:17
Closing this, as the original issue has been resolved by upgrading the library, and the subsequent feature request is [tracked separately](https://github.com/googleapis/python-bigquery/issues/62).

**Closed by plamut** 2020-03-24 13:17 UTC
Labels: api: bigquery, type: question
