### ISSUE TITLE
Conflict with auto_detect and skip_leading_rows

### ISSUE THREAD

**Issue by ykursav** [googleapis/python-bigquery#1608] opened 2023-07-10 18:55 UTC
Hi all,

Unfortunately, I cannot provide you code snippet or data as client specific but this is happening second time. Default value of skip_leading_rows just deciding to skipping row with data when you select auto_detect. Is it some expected behaviour? It mostly happens csv files with lots of quotes. I am using pandas dataframe to load data. Sorry for not able to provide more data.

Thanks for stopping by to let us know something could be better!

**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

Please run down the following list and make sure you've tried the usual "quick fixes":

  - Search the issues already opened: https://github.com/googleapis/python-bigquery/issues
  - Search StackOverflow: https://stackoverflow.com/questions/tagged/google-cloud-platform+python

If you are still having issues, please be sure to include as much information as possible:

#### Environment details

  - OS type and version: Windows 10
  - Python version: `python --version` 3.9.15
  - pip version: `pip --version`  23.0.1
  - `google-cloud-bigquery` version: `pip show google-cloud-bigquery` 3.7.0

#### Steps to reproduce

  1. I cannot share file as specific for my client. But use files with lots of quotes and separated with new lines.
  2. Auto detect should be enabled in job config.
  3. allow_quoted_lines should be enabled.
  4. Then when you run script and try to load the file. It skips the first row even skip_leading_rows default is 0.
  5. When you force skip_leading_rows=0 behaviour is disappearing and inserting first row.

#### Code example

```python
# example
```

#### Stack trace
```
# example
```

Making sure to follow these steps will guarantee the quickest resolution possible.

Thanks!

**Comment by chalmerlowe** [comment] 2023-07-14 15:52
@ykursav I am not sure how to assist in this matter without:

* any code samples
* any data examples

Can this be reproduced with a simple dummy data set and a simple example script that you can share with us?
Reducing it down to a minimum viable example that still fails in the same way as your customer's more complicated and proprietary code and providing a stack trace that shows the error will go a long way toward:

* proving that the issue is actually a bigquery issue (and not a data issue OR pandas issue, etc)
* providing some insight into what is causing the problem and where in the code base to start looking

Without additional info and context, I will likely close this issue as could not reproduce.

**Comment by chalmerlowe** [comment] 2023-08-16 20:06
Closing due to lack of response.
Will not fix.

**Closed by chalmerlowe** 2023-08-16 20:06 UTC
Labels: api: bigquery, status: will not fix
