### ISSUE TITLE
Cannot import module: ModuleNotFoundError: No module named 'pytz'

### ISSUE THREAD

**Issue by bobidle** [googleapis/python-bigquery#1589] opened 2023-06-21 11:59 UTC
Noticed an issue with module version 1.28.3, if that module version is still supported please fix the following issue. Thank you very much.

#### Environment details

  - OS type and version: Debian Linux 11.7
  - Python version: 3.9.2
  - pip version: pip 20.3.4 from /usr/lib/python3/dist-packages/pip (python 3.9)
  - `google-cloud-bigquery` version: ` 1.28.3

#### Steps to reproduce

  1. install `google-cloud-bigquery==1.28.3` via pip
  2. run example code

#### Code example

```python
from google.cloud import bigquery
```

#### Stack trace
```
  File "/home/user/bigquery/test.py", line 1, in <module>
    from google.cloud import bigquery
  File "/home/user/.local/lib/python3.9/site-packages/google/cloud/bigquery/__init__.py", line 35, in <module>
    from google.cloud.bigquery.client import Client
  File "/home/user/.local/lib/python3.9/site-packages/google/cloud/bigquery/client.py", line 62, in <module>
    from google.cloud.bigquery.dataset import Dataset
  File "/home/user/.local/lib/python3.9/site-packages/google/cloud/bigquery/dataset.py", line 27, in <module>
    from google.cloud.bigquery.table import TableReference
  File "/home/user/.local/lib/python3.9/site-packages/google/cloud/bigquery/table.py", line 24, in <module>
    import pytz
ModuleNotFoundError: No module named 'pytz'
```

Related issue: https://github.com/googleapis/python-bigquery/issues/885

**Comment by meredithslota** [comment] 2023-06-22 03:15
Hi there — thanks for reporting this! As you noted, this is a duplicate of this issue: https://github.com/googleapis/python-bigquery/issues/885 We do keep a v1 branch alive for high-priority fixes but since we didn't backport this at the time, it may not qualify.

**Comment by chalmerlowe** [comment] 2023-06-23 12:04
A while back, `api-core` dropped the `pytz` dependency which our older `python-bigquery` library implicitly depends on.

A workaround is to install `pytz` manually if using an older BigQuery client version. 
Based on manpower and priorities, I don't see us working on this right away.

A change related to this was made in a `2.x` version of `python-bigquery` ([linking here for posterity](https://github.com/googleapis/python-bigquery/pull/875/files)):

I recommend closing this.

**Closed by chalmerlowe** 2023-06-23 12:04 UTC
Labels: api: bigquery, type: bug, priority: p3
