### ISSUE TITLE
Raised `ArrowTypeError` should indicates which column is causing the error

### ISSUE THREAD

**Issue by aaaaahaaaaa** [googleapis/python-bigquery#1822] opened 2024-02-20 16:20 UTC
Debugging typing errors when working with existing tables with a large number of columns is extremely frustrating, to say the least: the `pyarrow` error never indicates which column is causing the issue.

It would be an absolute life saver if more debugging information were raised with the exception.

E.g.:
```
pyarrow.lib.ArrowTypeError: object of type <class 'str'> cannot be converted to int
```

**Comment by Linchin** [comment] 2024-02-20 21:54
Thank you @aaaaahaaaaa for raising the issue. This error message seems to be raised directly by pyarrow, and we might be able to wrap some more useful information outside of it. Could you provide a minimal code snippet that reproduces the issue, so I can locate the exact place the exception is raised?

**Comment by aaaaahaaaaa** [comment] 2024-02-21 10:27
Here is a minimal example:

```python
import google.auth
import pandas as pd
from google.cloud import bigquery

credentials, project = google.auth.default()

client = bigquery.Client(credentials=credentials, project=project)
table_id = "TABLE_ID"

data = {"what": "ever"}
df = pd.DataFrame([data])

job_config = bigquery.LoadJobConfig(schema=[bigquery.SchemaField("what", "INTEGER")])

job = client.load_table_from_dataframe(df, table_id, job_config=job_config)
job.result()
```

Error (doesn't show any debugging information referring to the column `what`):
```
pyarrow.lib.ArrowInvalid: Could not convert 'ever' with type str: tried to convert to int64
```

**Comment by chalmerlowe** [comment] 2024-03-11 14:46
At this time, I am pushing to get PR #1836 finished so we can close this out.

It appears that we have about three PRs generated by three different folks that are related and focused on similar problems. Aiming to have #1836 be the main focal point and will close out the other two PRs. Unique characteristics of each, where reasonable, will be incorporated into #1836.

**Closed** 2024-03-19 13:51 UTC
Labels: api: bigquery, type: feature request, priority: p3
