### ISSUE TITLE
Using string array with magic block results in whitespace removal from first entry of the array

### ISSUE THREAD

**Issue by amardeep** [googleapis/python-bigquery#166] opened 2020-07-14 08:34 UTC
On passing a dict ` { 'cats': ['apple orange', 'pear plum']}` as params in bigquery magic cell, the first value is changed to `appleorange` - the space character is filtered out.

#### Environment details

  - OS type and version: colab
  - Python version: Python 3.6.9
  - pip version: 19.3.1
  - `google-cloud-bigquery` version: 1.21.0

#### Steps to reproduce

A colab notebook illustrating the error:
https://colab.research.google.com/gist/amardeep/63ec303ba8bac3db9849f4044cd19ff1/test-bigquery-array-parameter-bug.ipynb
  
#### Code example

```python
params = {
    'cats': ['apple orange', 'pear plum']
}

%%bigquery  --params $params
SELECT * FROM UNNEST(@cats)
```

This results in the output:
```
           f0_
0  appleorange
1    pear plum
```

**Comment by HemangChothani** [comment] 2020-07-15 11:43
@amardeep The problem is related to the `IPython` library which used for the magics , the `magic_arguments.parse_argstring` method consider first element of list as a two different element so when we use `join()` method  element will be merged.

@plamut Cloud you help in this , i don't have that much idea about the `IPython` 's limitation.

**Comment by plamut** [comment] 2020-07-17 13:06
@HemangChothani @amardeep This appears as a yet another case where IPython's argument parsing proves to be fragile in some cases. It's the same reason why negative numbers in `$params` variable would be incorrectly recognized as additional arguments ([details](https://github.com/googleapis/python-bigquery/issues/108#issuecomment-637554556)). The workaround also mentioned there is to pass `params` as a JSON string variable.

Perhaps the [docs](https://googleapis.dev/python/bigquery/latest/magics.html#module-google.cloud.bigquery.magics) on the `--params`  option are not clear enough (they only mention the negative numbers case), but aside from possibly further improving the wording I don't think this issue can be reliably fixed in the client library itself.

**Comment by amardeep** [comment] 2020-07-17 16:47
It doesn't work with JSON string.

```python
params = {
    'cats': ['apple orange', 'pear plum']
}
jparams = json.dumps(params)
jparams
```

```
'{"cats": ["apple orange", "pear plum"]}'
```

```python
%%bigquery df --params $jparams
SELECT * FROM UNNEST(@cats)
```

```
           f0_
0  appleorange
1    pear plum
```

**Comment by HemangChothani** [comment] 2020-07-20 05:14
@plamut Yes, Actually i am not  available for few days, so please take a look into it when you get some time, thanks.

**Comment by plamut** [comment] 2020-07-20 08:55
The following argument string:
```
 --params {'cats': ['apple orange', 'pear plum']}
```

is tokenized by IPython as follows:
- `--params`
- `{'cats':`
- `['apple`
- `orange',`
- `'pear plum'`
- `]}`

The parser is not aware of dicts, lists, and similar structures, thus it does not treat them as a single entity and splits them into multiple tokens. On the other hand it does appear that the parser at least recognizes multi-word strings if they are enclosed in quotes, which is why it produces `'pear plum'` as a single token.

It made me wondering if we could trick the parser to treat the first array item, i.e. `'apple orange'` the same, and it turned out that if we inject a space between `[` and `'`, we can get around the issue.

```py
>>> params = {
...         'cats': ['apple orange', 'pear plum', 'foo bar']
... }
>>> params_json = json.dumps(params)
>>> with_space = params_json.replace('["', '[ "')
>>> with_space
'{"cats": [ "apple orange", "pear plum", "foo bar"]}'
```

Such modified JSON string gets tokenized as follows:
- `--params`
- `{"cats":`
- `[`
- `"apple orange"`
- `"pear plum"`
- ...

The space between "apple" and "orange" is not lost anymore and correct result is produced:
```py
%%bigquery df --params $with_space
SELECT * FROM UNNEST(@cats)

            f0_
0  apple orange
1     pear plum
2       foo bar
```

Such manipulation of JSON strings is of course far from ideal, but at least it's straightforward and should work in most cases. We are kind of limited with IPython's argument parser here.

**Comment by amardeep** [comment] 2020-07-22 09:31
Other option to consider is not using IPython argument parser, and custom parse line argument.

**Comment by plamut** [comment] 2020-07-22 11:27
Considering the different edge cases reported where the built-in parser falls flat, we might actually have to do this at some point, yes. The replacement parser would of course have to be compatible with the existing ones in order to not break existing notebooks.

**Closed** 2020-09-09 20:21 UTC
Labels: api: bigquery, priority: p2, type: bug
