### ISSUE TITLE
Schedule parameter not available (big query)

### ISSUE THREAD

**Issue by Iuiu1234** [googleapis/python-bigquery#97] opened 2020-05-07 13:26 UTC
Using bq from bash (google cloud sdk) there is the parameter 'shedule' to schedule the query.
But I can't see that argument as any of the function in the package (quey, job_configuration)

**Comment by HemangChothani** [comment] 2020-05-11 05:09
Closing this issue as it's duplicate of https://github.com/googleapis/python-bigquery/issues/96

**Closed by HemangChothani** 2020-05-11 05:09 UTC
Labels: api: bigquery, triage me
