### ISSUE TITLE
insert_rows_json failing when passing a table

### ISSUE THREAD

**Issue by jramosss** [googleapis/python-bigquery#1278] opened 2022-06-15 15:56 UTC
#### Environment details

  - Ubuntu 20.04
  - Python 3.8
  - pip 20.0.2
  - `google-cloud-bigquery` version: 3.2.0

#### Steps to reproduce

  1. Create a table using bigquery.Client().create_table("{project_id}.{dataset_id}.{table_id}")
  2. Call insert_rows_json(table, table_to_insert, row_ids=[None] * len(table_to_insert)) where table is the table created in step 1 and table_to_insert is a list of dicts

#### Code example

```python
    @staticmethod
    def get_table(client: BigQueryClient, table_id: str):
        print(f"Table id to get: {table_id}")
        try:
            table = client.get_table(table_id)
        except Exception:
            table = client.create_table(table_id)
        return table

    def set_table_schema(self, client: BigQueryClient, table: Table):
        table.schema = SHEET_TABLE
        client.update_table(table, ["schema"])

    def insert_row(self, row: List[str]):
        bq_client = BigQueryClient(project=self.data.get("project_id"))
        table_id = self.data.get("table_id")
        table = self.get_table(bq_client, table_id)
        table_to_insert = self.create_json_table(row)
        if not table.schema:
            self.set_table_schema(bq_client, table)
        bq_client.insert_rows_json(
            table,
            table_to_insert,
            row_ids=[None] * len(table_to_insert)
        )
```

#### Stack trace
```
___________________________ TestsInsertRow.test_insert_row_no_existent_table ____________________________
api/platforms/google/bigquery/tests/test_bigquery_insert_row.py:28: in test_insert_row_no_existent_table
    client.insert_row(row)
api/platforms/google/bigquery/datasets.py:85: in insert_row
    bq_client.insert_rows_json(
.venv/lib/python3.8/site-packages/google/cloud/bigquery/client.py:3597: in insert_rows_json
    response = self._call_api(
.venv/lib/python3.8/site-packages/google/cloud/bigquery/client.py:759: in _call_api
    return call()
.venv/lib/python3.8/site-packages/google/api_core/retry.py:286: in retry_wrapped_func
    return retry_target(
.venv/lib/python3.8/site-packages/google/api_core/retry.py:189: in retry_target
    return target()
.venv/lib/python3.8/site-packages/google/cloud/_http/__init__.py:494: in api_request
    raise exceptions.from_http_response(response)
E   google.api_core.exceptions.NotFound: 404 POST https://bigquery.googleapis.com/bigquery/v2/projects/infoxel-tagx/datasets/sheets_testing/tables/non_existent_table/insertAll?prettyPrint=false: Table 483170507439:sheets_testing.non_existent_table not found.
```

**Comment by steffnay** [comment] 2022-06-17 18:17
Hey, @jramosss, it looks like you want to check that your information for the table you're creating and inserting into is correct because the issue is that the table is not being found.
```
Table 483170507439:sheets_testing.non_existent_table not found
```

**Comment by steffnay** [comment] 2022-06-17 20:44
I'm closing this issue because I looked more closely at the code sample provided and was unable to reproduce this issue.

**Closed by steffnay** 2022-06-17 20:44 UTC
Labels: api: bigquery, type: question

**Comment by jramosss** [comment] 2022-06-18 16:25
But my function get_table is a get or create, so how come i can get the table with .get_table without errors, but when i try to insert data to that table it throws 404?

**Comment by tomhamiltonstubber** [comment] 2023-11-30 14:14
I'm also getting this issue. The table exists when I list it but I'm getting 404 when attempting to write. It's intermittent.
