### ISSUE TITLE
Reading the labels set on a job fails

### ISSUE THREAD

**Issue by rholloway** [googleapis/python-bigquery#469] opened 2021-01-11 22:27 UTC
The ability to specify labels on created BigQuery jobs was supposedly added in googleapis/google-cloud-python#5654, but it doesn't work. There is also a comment in the documentation from that same PR referring to Client.update_job() which doesn't even exist.

#### Environment details

# python --version
Python 3.7.3

# pip freeze | grep google
google-api-core==1.24.1
google-auth==1.24.0
google-cloud-bigquery==2.6.2
google-cloud-bigtable==1.6.1
google-cloud-core==1.5.0
google-cloud-pubsub==2.2.0
google-cloud-storage==1.35.0
google-crc32c==1.1.0
google-resumable-media==1.2.0
googleapis-common-protos==1.52.0
grpc-google-iam-v1==0.12.3

#### Code example

```python
job_config = bigquery.QueryJobConfig(labels={"app": "test"})
query_job = client.query("SELECT 1", job_config=job_config)

# no labels seen below
print(query_job.labels)

# try and get a job later, also no labels
job = client.get_job(query_job.job_id)
print(job.labels)

```

**Comment by plamut** [comment] 2021-01-13 13:57
@rholloway Thanks for the report, I can confirm the reported behavior.

It turns out the labels are actually present in the raw job data, i.e. in `query_job._properties["configuration"]["labels"]`, but the `labels` property tries to read them from `self._properties["labels"]`. If that's the only cause, it should be an easy fix.

**Comment by rarredon** [comment] 2021-01-13 15:03
@plamut I can confirm that there's a workaround by going through the job's configuration. In my case, I was able to submit a job with labels and then later access them as follows
```
client = BigQueryClient()
job = client.submit_job(sql, labels={'foo': 'bar'})
...
job = client.get_job(job.job_id)
print(job._configuration.labels)  # {'foo': 'bar'}
```

Perhaps the `_configuration` attr is synonymous with `_properties['configuration']`, just as you found. I hope that helps.

**Comment by plamut** [comment] 2021-01-13 15:13
@rarredon Indeed, semantically they represent [the same](https://github.com/googleapis/python-bigquery/blob/2788736b80a4c4ac0ae3029aeb28bcefd34f2db7/google/cloud/bigquery/job/query.py#L542) thing. :+1:
`_configuration` is a  `QueryJobConfig()` instance, while `_properties["configuration"]` is the former's "raw" form (a nested dict structure).

**Comment by plamut** [comment] 2021-01-14 09:27
Got an update from the backend maintainers - the labels on the jobs are immutable once a job is created, thus the client cannot  update them even if it wanted to.

It still needs to read them from the correct nesting level, of course, which will be fixed soon.

**Closed** 2021-01-14 15:59 UTC
Labels: api: bigquery, priority: p2, type: bug
