### ISSUE TITLE
Stored procedure with positional parameters is slow

### ISSUE THREAD

**Issue by baggio002** [googleapis/python-bigquery#566] opened 2021-03-22 00:49 UTC
Using positional parameters in stored procedure call is slower than using hard-coded values or named parameters 3-4 times

#### Environment details

  - OS type and version: CentOS 7
  - Python version: Python 3.6.8
  - pip version: pip 21.0.1
  - `google-cloud-bigquery` version: 2.12.0

#### Steps to reproduce

 Call stored procedure:

  1. try hard-coded values or named parameters
  2. using positional parameters

The situation (2) is slower than (1)  3-4 times

#### Code example
1. try named parameters
```python
from google.cloud import bigquery
import sys

DATASET=<dataset>
print(DATASET)

client = bigquery.Client()
lSql="$DATASET.parameter_test_8(null,null,null,null,null,null,null,@a)"
print(lSql)
job_config = bigquery.QueryJobConfig(
    query_parameters=[
        bigquery.ScalarQueryParameter('a', "STRING", "2020-10-26"),
    ]
)
query_job = client.query(lSql,job_config=job_config)

for row in query_job:
    print(row)
```

2. using positional parameters
```python
from google.cloud import bigquery
import sys

DATASET=<dataset>
print(DATASET)

client = bigquery.Client()
lSql="$DATASET.parameter_test_8(null,null,null,null,null,null,null,?)"
print(lSql)
job_config = bigquery.QueryJobConfig(
    query_parameters=[
        bigquery.ScalarQueryParameter(None, "STRING", "2020-10-26"),
    ]
)
query_job = client.query(lSql,job_config=job_config)

for row in query_job:
    print(row)
```

SQL
```sql
CREATE OR REPLACE PROCEDURE <DATASET>.parameter_test_8(a7 STRING, a6 STRING, a5 STRING, a4 STRING, a3 STRING, a2 STRING, a1 STRING, p STRING)
begin 

declare lReportDt string;

set lReportDt='2020-10-26';

end
```

#### result:
1. try named parameters
real    0m2.738s
user    0m0.504s
sys     0m0.055s

2. using positional parameters
real    0m10.637s
user    0m0.500s
sys     0m0.052s

Could you please solve or optimize this issue?

Thanks!

**Comment by plamut** [comment] 2021-03-22 11:38
I can reproduce this, although the difference is not that drastic on my machine - but still significant. 

Used Python 3.8 for the test (FWIW, the timings are comparable to Python 3.6):

**Named parameters:**
```
CALL `<DATASET>.parameter_test_8`(null,null,null,null,null,null,null,@a)

real    0m2.476s
user    0m0.983s
sys     0m0.456s
```

**Positional parameters:**
```
CALL `<DATASET>.parameter_test_8`(null,null,null,null,null,null,null,?)

real    0m5.178s
user    0m0.949s
sys     0m0.400s
```

Since the amounts of `user` and `sys` time used are comparable, it appears the difference happens on on the backend, but I'll have to do some more detailed profiling to confirm that.

**Comment by idcipher106** [comment] 2021-03-22 12:08
Hello, I work at the company that reported this issue to Google, and I can add that this is not related to python.  We have tested positional parameters to BigQuery procedures through a number of interfaces (including python), and all exhibit the same latency problem.

**Comment by plamut** [comment] 2021-03-22 12:11
@idcipher106 Thanks for further confirming the findings, this indeed does not seem to be a specific problem in the Python client itself.

**Comment by shollyman** [comment] 2021-03-22 16:25
Given the latency appears to be backend specific, would one of you mind filing the issue on the [BigQuery public issue tracker](https://cloud.google.com/bigquery/docs/getting-support#issuetracker)?  This issue tracker is only for the python client library specifically.

**Comment by idcipher106** [comment] 2021-03-23 13:32
I created this:  https://issuetracker.google.com/183408442

I welcome any advice to expedite resolution of this problem.  We have a tight deadline to deliver a project and this is a blocker.

**Comment by shollyman** [comment] 2021-03-24 22:09
I've forwarded the public issue to one of the engineers more familiar with parameter binding to investigate.  Any further updates will occur via the public tracker issue you created, so I'll go ahead and close this one.

Thanks for reaching out, and for having such a clean repro to demonstrate the impact.

**Closed by shollyman** 2021-03-24 22:09 UTC
Labels: api: bigquery, external, priority: p2, type: bug
