### ISSUE TITLE
 QueryJobConfig does not seem to take into account the schema of the destination table.

### ISSUE THREAD

**Issue by francois-baptiste** [googleapis/python-bigquery#73] opened 2020-04-06 14:49 UTC
QueryJobConfig does not seem to take into account the schema of the destination table.
It looks like a bug to me.

```python
from google.cloud import bigquery

schema=[bigquery.SchemaField('id', 'INTEGER', 'REQUIRED', None, ()),
 bigquery.SchemaField('tag_name', 'STRING', 'REQUIRED', None, ()),
 bigquery.SchemaField('count', 'INTEGER', 'REQUIRED', None, ()),
 bigquery.SchemaField('excerpt_post_id', 'INTEGER', 'REQUIRED', None, ()),
 bigquery.SchemaField('wiki_post_id', 'INTEGER', 'REQUIRED', None, ())]

table_id='myproject.mydataset.mytable'

job_config = bigquery.QueryJobConfig()
job_config.destination = table_id
job_config.schema=schema

sql = """
    SELECT id, REVERSE(tag_name) as tag_name, count, excerpt_post_id, wiki_post_id
    FROM `bigquery-public-data.stackoverflow.tags`
"""

query_job = client.query(sql, job_config=job_config)
query_job.result()

<google.cloud.bigquery.table.RowIterator object at 0x7f52a8dfca58>
```
```python
>>> client.get_table('myproject.mydataset.mytable').schema
[SchemaField('id', 'INTEGER', 'NULLABLE', None, ()),
 SchemaField('tag_name', 'STRING', 'NULLABLE', None, ()),
 SchemaField('count', 'INTEGER', 'NULLABLE', None, ()),
 SchemaField('excerpt_post_id', 'INTEGER', 'NULLABLE', None, ()),
 SchemaField('wiki_post_id', 'INTEGER', 'NULLABLE', None, ())]
```

**Comment by plamut** [comment] 2020-04-07 09:58
@francois-baptiste I can confirm the reported behavior, thanks for the good example.

The question is, however, what is the expected result if an explicit schema is provided?
 - If the schema matches the source table schema, it is redundant anyway.
 - If the schema differs from the source table schema, an implicit conversion between the two should be made, but this can quickly turn problematic with incompatible fields.

Generally, schema changes can be configured through `QueryJobConfig.schema_update_options`, but the options are [pretty limited](https://cloud.google.com/bigquery/docs/reference/rest/v2/Job#JobConfigurationQuery.FIELDS.schema_update_options). 

It might make sense to at least issue a warning if a schema is provided, but will not be used in the respective query/load operation, what do you think?

---

FWIW, in this particular case when the explicit schema declared the fields as REQUIRED, a workaround can be made (to a degree) by creating the destination table before storing the query results into it:
```py
schema = [
    bigquery.SchemaField('id', 'INTEGER', 'REQUIRED', None, ()),
    bigquery.SchemaField('tag_name', 'STRING', 'REQUIRED', None, ()),
    bigquery.SchemaField('count', 'INTEGER', 'REQUIRED', None, ()),
    bigquery.SchemaField('excerpt_post_id', 'INTEGER', 'NULLABLE', None, ()),
    bigquery.SchemaField('wiki_post_id', 'INTEGER', 'NULLABLE', None, ())
]
dest_table = bigquery.Table(dest_table_ref, schema=schema)
client.create_table(dest_table)
# load data into dest_table_ref now...
```
The above worked, but I still had to declare the last two columns as NULLABLE, because there are some NULLs in the source table. The rest of the simple changes did not succeed, e.g. specifying an INTEGER column as FLOAT, the backend rejected such schema mismatch.

**Comment by francois-baptiste** [comment] 2020-04-07 11:53
Thank you @plamut for your comprehensive explaination.
Yes a warning message might be a good thing, especially for new users.

**Comment by plamut** [comment] 2020-04-07 12:24
@francois-baptiste I will check with the product people if "schema unused" can reliably be determined by the client itself, and add a warning if that's the case. I'm glad the explanation was useful to you.

**Comment by plamut** [comment] 2020-04-08 13:15
@francois-baptiste I have an update - the logic whether a schema is (not) used in a query job is complex and depends on multiple factors, and is not a simple quick check. Replicating that logic in the client library would be non-trivial, and could easily get out sync with the server-side logic.

On the plus side, there are plans to considerably improve the end user documentation on that topic, and better explain the cases when the schema is (not) used.

**Comment by shollyman** [comment] 2023-02-01 21:25
https://cloud.google.com/bigquery/docs/schema-detect#auto-detect documents some of the nuances of detected vs reference schema rules, particularly the format implications.  I'm going to close this issue, but if there's more you'd like to see documented regarding the service behavior I'd recommend filing an issue either through the feedback widget in docs, or via the [public issue tracker](https://cloud.google.com/bigquery/docs/getting-support#issuetracker).

**Closed by shollyman** 2023-02-01 21:25 UTC
Labels: api: bigquery, type: feature request
