### ISSUE TITLE
load_table_from_dataframe should honor default project and dataset.

### ISSUE THREAD

**Issue by jimfulton** [googleapis/python-bigquery#843] opened 2021-08-02 14:20 UTC

**Comment by steffnay** [comment] 2022-04-16 04:46
@jimfulton Can you please clarify where you're requesting the default dataset value be used within this method?

**Comment by Linchin** [comment] 2024-02-02 23:50
I will close this issue due to lack of details and inability to reproduce.

**Closed by Linchin** 2024-02-02 23:50 UTC
Labels: api: bigquery, type: feature request
