### ISSUE TITLE
BigQuery: Upload STRUCT / RECORD fields from load_table_from_dataframe

### ISSUE THREAD

**Issue by tswast** [googleapis/python-bigquery#21] opened 2019-05-30 00:37 UTC
**Is your feature request related to a problem? Please describe.**

If you have a pandas Series containing dictionaries, ideally this could be uploaded to BigQuery as a STRUCT / RECORD column. Currently this fails with a "file does not exist error" because the arrow write_table fails with ""ArrowInvalid: Nested column branch had multiple children".

**Describe the solution you'd like**

Upload of a RECORD column succeeds. This will require a fix to https://jira.apache.org/jira/browse/ARROW-2587.

**Describe alternatives you've considered**

Change intermediate file format to JSON or some other type. This isn't ideal, since most other types are row-oriented, but pandas DataFrames are column-oriented.

**Comment by meredithslota** [comment] 2020-03-27 17:54
https://jira.apache.org/jira/browse/ARROW-2587 is still open. I'm not sure what we are able to do until that is fixed.

**Comment by emkornfield** [comment] 2020-03-29 06:06
Writing nested structs will be fixed in Arrow 0.17.0 release (sometime in the next few weeks).

**Comment by plamut** [comment] 2020-03-31 10:49
I can confirm that the error from the issue description is not reproducible anymore with the latest `pyarrow` (development version, compiled from source).

I was able to successfully load the following data:
```py
schema = [
    bigquery.SchemaField(
        "bar",
        "STRUCT",
        fields=[
            bigquery.SchemaField("aaa", "INTEGER", mode="REQUIRED"),
            bigquery.SchemaField("bbb", "INTEGER", mode="REQUIRED"),
        ],
        mode="REQUIRED",
    ),
]

dict_series = [
    {"aaa": 1, "bbb": 2}, {"aaa": 3, "bbb": 4}, {"aaa": 5, "bbb": 6}
]
df = pd.DataFrame(data={"bar": dict_series}, columns=["bar"])

job_config = bigquery.LoadJobConfig(schema=schema)
client.load_table_from_dataframe(
    df, "my.table.reference", job_config=job_config
).result()
```

This resulted in the following table on the backend:

| Row | bar.aaa | bar.bbb |
|---|---|---|
1 | 1 | 2
2 | 3 | 4
3 | 5 | 6

**Comment by MainHanzo** [comment] 2020-04-10 12:46
Hello, I am very interested in this feature and I would love to compile the latest pyarrow from source.
Could you please give me some guides on how to compile it locally? I haven't found any instructions on how to build this project.

**Comment by plamut** [comment] 2020-04-10 13:02
@MainHanzo Fortunately, compiling from source is not needed, as the `pyarrow` maintainers made the nightly pre-release builds available ([comment](https://github.com/googleapis/python-bigquery/issues/63#issuecomment-606708787)).

**Comment by jack-tee** [comment] 2020-07-10 16:20
Should this be fixed now? I'm using pyarrow 0.17.1 and google-cloud-bigquery 1.25.0.
If I take a dataframe and pass it to .load_table_from_dataframe() if the **table does not** exist in bigquery then it loads the struct field correctly.
If the table **already exists** I get this error and a link to this page? `Caused by: Uploading dataframes with struct (record) column types is not supported.`

**Comment by plamut** [comment] 2020-07-11 09:09
@jack-tee AFAIK it should be fixed in `pyarrow`, yes, although only for Python 3.

The error you are seeing is [raised](https://github.com/googleapis/python-bigquery/pull/146/files#diff-1be019f1d3367deecade9437089009d8R291-R297) by the client library itself. There is a PR that will remove this error-raising part, but it's not merged yet (it's actually put on hold, because it only works in Python 3 and we are dropping Python 2 support in the near future anyway).

How urgently do you need the fix?

If feasible, you can temporarily manually comment out the linked code block until the fix gets actually released.

**Comment by jack-tee** [comment] 2020-07-13 14:23
Thanks for clarifying @plamut. When I saw that I could load struct fields into a table that didn't exist but not into an existing table I thought perhaps that path had been missed, but your explanation makes sense.

I can work around it for now. Thanks :)

**Closed** 2020-08-03 04:47 UTC
Labels: api: bigquery, status: blocked, type: feature request
