### ISSUE TITLE
Timezone information is lost when to_dataframe() is used

### ISSUE THREAD

**Issue by prashastk** [googleapis/python-bigquery#141] opened 2020-06-18 21:25 UTC
#### Environment details

  - OS type and version: macOS 10.15.5 
  - Python version: Python 3.6.10
  - pip version: pip 20.1 
  - `google-cloud-bigquery` version: Version: 1.25.0

#### Steps to reproduce

  1. Query any table with timestamp field
  2. print a row with timestamp field:
`datetime.datetime(2020, 5, 23, 0, 14, 44, 706000, tzinfo=<UTC>)`
  3. Re-run the quer, this time use `to_dataframe()` and print a row with a timestamp field:
`datetime.datetime(2020, 5, 23, 0, 14, 44, 706000)`

tzinfo is lost after doing `to_dataframe()`!

**Comment by HemangChothani** [comment] 2020-06-22 12:34
@prashastk I am not able to reproduce, so can you please check my steps and let me know if I missed something?

**Table Schema:**

    [
     SchemaField('contractId', 'INTEGER', 'REQUIRED', None, (), None),
     SchemaField('contractTypeId', 'INTEGER', 'REQUIRED', None, (), None),
     SchemaField('created', 'TIMESTAMP', 'REQUIRED', None, (), None)
    ]


```python
    from google.cloud import bigquery
    client = bigquery.Client()

    result = client.list_rows('projectid.datasetid.tableid')
    df = result.to_dataframe()
```
    print (df.types)
    contractId                      int64
    contractTypeId                  int64
    created           datetime64[ns, UTC]


**Output:**
df ['created'] = 2019-12-06 17:09:11.317689+00:00 (where `00:00` shows the tzinfo)

or

df['created'].to_list() gives `[Timestamp('2019-12-06 17:09:11.317689+0000', tz='UTC')]`

**Comment by prashastk** [comment] 2020-06-22 16:28
@HemangChothani looks like the issue is specific to timestamp fields within records.

**Table schema:**
```
[
  SchemaField('cell_id', 'RECORD', 'NULLABLE', None,
     (SchemaField('time', 'TIMESTAMP', 'NULLABLE', None, (), None),
      SchemaField('number', 'INTEGER', 'NULLABLE', None, (), None)), None),
  SchemaField('run_start_time', 'TIMESTAMP', 'NULLABLE', None, (), None)
]
```

**This is without dataframe:**
run_start_time and cell_id.time both have timezone
```
row = next(iter(result))
print(row.run_start_time)
2020-05-23 00:03:27.994000+00:00
print(row.cell_id)
{'time': datetime.datetime(2020, 5, 23, 0, 3, 39, 848000, tzinfo=<UTC>), 'number': 204}
```

**This is with dataframe:**
run_start_time has timezone but cell_id.time does not have timezone
```
df = result.to_dataframe()
print(df.run_start_time[0])
2020-05-23 00:03:27.994000+00:00
print(df.cell_id[0])
{'time': datetime.datetime(2020, 5, 23, 0, 3, 39, 848000), 'number': 204}
```

**Comment by HemangChothani** [comment] 2020-06-23 10:16
@prashastk  We don't have any logic to convert from the API response types to pandas dtypes unless the dtypes. I think pandas convert struct type to the object and doesn't consider the nested datatype.

@emkornfield Another issue related to `to_dataframe`,  it converts `timestamp[us, tz=UTC]` to `datetime64[ns, UTC]` but when it is struct type like `struct<item_code: int64, time: timestamp[us, tz=UTC]>`then it gives `datetime64[ns]`. Do you have any information regarding that?

@plamut Do you have any idea about this kind of issue? thanks in advance.

**Comment by emkornfield** [comment] 2020-06-23 16:10
Looks like this might be an issue in [pyarrow](https://github.com/apache/arrow/blob/master/cpp/src/arrow/python/arrow_to_pandas.cc#L653)

**Comment by plamut** [comment] 2020-06-23 18:14
@HemangChothani There are quite a few issues related to type conversions that have their root causes in external libraries (`pyarrow`, for instance). I pointed this out today at a meeting to come up with a general strategy of tackling that.

(no immediate action plan yet, though)

**Comment by emkornfield** [comment] 2020-06-25 02:52
I opened [ARROW-9223](https://issues.apache.org/jira/browse/ARROW-9223) to track this.

**Comment by emkornfield** [comment] 2020-07-18 21:48
This should be fixed in the next release of Arrow (RC candidate is currently undergoing voting).  There still might be some oddities with List[Timestamp] I haven't test those.

**Comment by plamut** [comment] 2020-07-20 09:06
@emkornfield Sounds promising, thanks for the heads-up!

**Comment by emkornfield** [comment] 2020-07-21 03:49
My PR is reverted so likely won't be until next release :(

**Comment by meredithslota** [comment] 2020-12-28 20:14
It looks like the linked issue is marked resolved (https://issues.apache.org/jira/browse/ARROW-9223) with fixVersion 1.0.0 and we require pyarrow version >= 1.0.0 so hopefully this is fixed? Closing out but please reopen if this persists.

**Closed by meredithslota** 2020-12-28 20:14 UTC
Labels: :rotating_light:, api: bigquery, priority: p2, type: bug
