### ISSUE TITLE
Please install the 'db-dtypes' package to use this function ERROR while using google big query

### ISSUE THREAD

**Issue by archiejainbounteous** [googleapis/python-bigquery#1767] opened 2024-01-11 18:04 UTC
I am facing db-dtypes issues while running the following code. Pls note that db_types is installed.

```
os.environ["GOOGLE_APPLICATION_CREDENTIALS"] = json_path
client = bigquery.Client(project=project_name)

query = f"""
            select * from `tabel_name`
            limit 100
        """
df = client.query(query).to_dataframe()

df.head()
```

```
ERROR---> ~/Library/Python/3.9/lib/python/site-packages/google/cloud/bigquery/_pandas_helpers.py:970     raise ValueError(_NO_DB_TYPES_ERROR) from db_dtypes_import_exception

ValueError: Please install the 'db-dtypes' package to use this function.
```

**Comment by chalmerlowe** [comment] 2024-01-18 15:11
@archiejainbounteous 

at this point, this is not a reproducible issue for me.

I ran code very similar to yours (using my own project, dataset, and tablenames of course).

It produced the expected results.

IF you are still having problems, I might consider doing some double checking to make sure that db-dtypes is installed where you think it is.

`pip freeze` or the analogous `conda` command may help with this task. 

I am going to close this issue as cannot reproduce.

**Closed by chalmerlowe** 2024-01-18 15:11 UTC
Labels: api: bigquery, status: will not fix

**Comment by omiguelpinheiro** [comment] 2024-08-01 13:52
I'm having the same problem on python 3.12.1

**Comment by chalmerlowe** [comment] 2024-08-01 15:00
I am not able to reproduce this.
I attempted to do so with these versions of the code:

db-dtypes==1.2.0
google-cloud-bigquery==3.17.2

My code displays the expected result without complaint.

This limits my ability to troubleshoot the problem.

**Comment by omiguelpinheiro** [comment] 2024-08-01 15:34
it was likely a problem with the jupyter environment. Restarting the kernel and running the code again fixed it.
