### ISSUE TITLE
protobuf-4.25.3 is incompatible with the library and results in an import error

### ISSUE THREAD

**Issue by kanakmi** [googleapis/python-bigquery#1830] opened 2024-02-26 01:29 UTC
#### Environment details

  - OS type and version: Debian 11
  - Python version: 3.10.8
  - pip version: 23.3.1
  - `google-cloud-bigquery` version: 3.17.2

#### Steps to reproduce

  1. Intall protobuf-4.25.3 
  2. Import bigquery

#### Code example

```python
from google.cloud import bigquery
```

#### Stack trace
```
line 14, in <module>
    from google.cloud import bigquery
  File "/opt/conda/default/lib/python3.10/site-packages/google/cloud/bigquery/__init__.py", line 35, in <module>
    from google.cloud.bigquery.client import Client
  File "/opt/conda/default/lib/python3.10/site-packages/google/cloud/bigquery/client.py", line 52, in <module>
    import google.api_core.exceptions as core_exceptions
  File "/opt/conda/default/lib/python3.10/site-packages/google/api_core/exceptions.py", line 29, in <module>
    from google.rpc import error_details_pb2
  File "/opt/conda/default/lib/python3.10/site-packages/google/rpc/error_details_pb2.py", line 20, in <module>
    from google.protobuf import descriptor as _descriptor
ImportError: cannot import name 'descriptor' from 'google.protobuf' (unknown location)
```

#### Recommendation
We tried re-installing bigquery but that didn't fix the error. Please mark protobuf-4.25.3 as incompatible in the dependencies.

**Comment by Linchin** [comment] 2024-02-26 19:38
Hi @kanakmi, thank you for raising the issue! I tried to reproduce the issue with the same versions, but I could import bigquery with no problem. I also checked protobuf-4.25.3, and [the descriptor module is present](https://github.com/protocolbuffers/protobuf/blob/v4.25.3/python/google/protobuf/descriptor.py). I suspect there's something wrong with your protobuf installation, so your python interpreter wasn't able to locate its path. I will close the issue now, but please let us know if you have any further questions!

**Closed by Linchin** 2024-02-26 19:38 UTC
Labels: api: bigquery

**Comment by kanakmi** [comment] 2024-02-27 09:14
Hey @Linchin 
Can you retry reproducing this bug on Debian 11?
I am facing this error in Google Dataproc clusters. On local system even I am unable to reproduce.

**Comment by Linchin** [comment] 2024-02-27 21:51
Hi @kanakmi, I ran the test on a google internal Debian that's somehow modified from the official Debian 11+. If we are unable to reproduce the issue in a different environment, I think it's more likely that the issue caused by something in the specific environment it's in. To really narrow down the possibilities, could you create a brand new virtual environment in your Google Dataproc clusters, and see if the issue persists? If not, maybe you can try the options in this [StackOverflow post](https://stackoverflow.com/questions/55657036/importerror-cannot-import-name-app-from-mypackage-unknown-location) and see if it helps? 

Please let me know how it goes!
