### ISSUE TITLE
pyarrow compatibility issue when instantiating a client

### ISSUE THREAD

**Issue by dpmcclurg** [googleapis/python-bigquery#890] opened 2021-08-20 16:33 UTC
Creating an SDK client using v2.24.1 in Databricks runtime v8.3 (Spark v3.1.1 and Python v3.8.8 and pyarrow v1.0.1) generates the following error: module 'pyarrow' has no attribute 'decimal256'.

pip version = 20.2.4

I tried:

1. Upgraded to [Databricks runtime v9.0](https://docs.databricks.com/release-notes/runtime/9.0.html) which brings Python down to v3.8.1 and pyarrow up to v4. **Same error as above and below**.
2. Reverted back to [Databricks runtime v8.3](https://docs.databricks.com/release-notes/runtime/8.3.html) (see specs above). Then, I downgraded BigQuery SDK to v2.24.0. **This resolved the error**.

![bq error](https://user-images.githubusercontent.com/82607747/130262745-f39a0085-2e5a-4e79-9df2-30fba9507ea2.PNG)

**Comment by plamut** [comment] 2021-08-23 09:16
@dpmcclurg Which `pyarrow` version do you have installed? What's the output of the following?
```py
import pyarrow; print(pyarrow.__version__)
```

As of BigQuery client version [v2.24.1](https://github.com/googleapis/python-bigquery/releases/tag/v2.24.1) released last week, `pyarrow >= 3.0.0` is required.

Has the `pyarrow` dependency been upgraded? I would check that first, and upgrade if necessary.

**Comment by tswast** [comment] 2021-09-01 14:54
This issue has also been reported in Beam and TFX.

Closing as a duplicate of https://github.com/googleapis/python-bigquery/issues/933

**Closed by tswast** 2021-09-01 14:54 UTC
Labels: api: bigquery, type: question
