### ISSUE TITLE
RowIterator `to_arrow` / `to_dataframe` doesn't respect "billing project" from QueryJob

### ISSUE THREAD

**Issue by tswast** [googleapis/python-bigquery#1422] opened 2022-11-23 23:18 UTC
Filing this for further investigation.

Despite setting the billing project in the client constructor https://github.com/ibis-project/ibis/blob/01bd4026e463984ab9fd17ea6d57ee6e42d50b8b/ibis/backends/bigquery/__init__.py#L169 and in the query method https://github.com/ibis-project/ibis/blob/01bd4026e463984ab9fd17ea6d57ee6e42d50b8b/ibis/backends/bigquery/__init__.py#L236 the `RowIterator` somehow ends up with the "data" project instead.

See: https://github.com/ibis-project/ibis/pull/4797#discussion_r1030883271

**Comment by tswast** [comment] 2022-11-23 23:21
Possibly a problem introduced here: https://github.com/googleapis/python-bigquery/blob/506f781c2dd775193336ab9432f32148250ed81d/google/cloud/bigquery/job/query.py#L1521

**Comment by tswast** [comment] 2022-11-23 23:24
Maybe not. Looks like it's getting the right project from the job reference. https://github.com/googleapis/python-bigquery/blob/76d88fbb1316317a61fa1a63c101bc6f42f23af8/google/cloud/bigquery/job/base.py#L239

**Comment by tswast** [comment] 2022-11-23 23:28
I see that project is used in the path here:
https://github.com/googleapis/python-bigquery/blob/506f781c2dd775193336ab9432f32148250ed81d/google/cloud/bigquery/client.py#L3837

But instead of using that project for `_project`, we're using the project from `client` https://github.com/googleapis/python-bigquery/blob/76d88fbb1316317a61fa1a63c101bc6f42f23af8/google/cloud/bigquery/table.py#L1518

Ideally, we'd use the same project as the one we use in the URL path.

Potential fix: add an optional `project` parameter to RowIterator and pass that in. We can still fallback to the client project if that isn't set.

**Comment by cpcloud** [comment] 2023-01-11 16:57
@tswast I can no longer reproduce this issue. Was it fixed at some point since you opened it?

**Comment by tswast** [comment] 2023-01-11 18:48
If so, it wasn't fixed intentionally. :-| Might be worth a unit test or even system test checking this.

**Comment by chalmerlowe** [comment] 2023-08-25 12:47
Per the above comment, the issue is no longer reproducible. Closing.

**Closed by chalmerlowe** 2023-08-25 12:47 UTC
Labels: api: bigquery, type: bug, priority: p3
