### ISSUE TITLE
rowIterator.to_dataframe removes any column named _partitiontime

### ISSUE THREAD

**Issue by mtagle** [googleapis/python-bigquery#1312] opened 2022-08-11 17:35 UTC
calling to_dataframe on a rowIterator containing a result with a column named "_partitiontime" (any capitalization of this results in the same issue) results in the dataframe dropping this column completely. 

Interestingly, it is NOT lost if _partitiontime is the only column in the result. Any other alias seems to work: `_pt`, `_partitiontim`, etc. This seems to exclusively to affect columns named `_partitiontime`. Any slight deviation from this name works.

Once upon a time, it seems like you were not allowed to have a bigquery result with _partitiontime column in it, but as far as I can tell that is no longer the case, and the row iterator contains this column without error. However, as soon as you convert the rowIterator to a dataframe, this column is lost.

I have to admit I have no idea where the bug is located, but I've narrowed it down quite concretely to .to_dataframe().

#### Environment details

  - OS type and version: Debian GNU/Linux 11 (bullseye)
  - Python version: 3.7.13
  - pip version: 22.2.2
  - `google-cloud-bigquery` version: 2.34.4

#### Steps to reproduce

You don't even need an ingestion-time partitioned table to reproduce this issue. Create any table with at least one column (we'll call it `aCol`) and at least one row.

```
client = # ... set up client
sql = "select aCol, aCol as _partitiontime from myDataset.myTable"
row_iter = client.query(sql).result()
print (row_iter.schema)
df = row_iter.to_dataframe()
```

Notice that the `row_iter` schema contains both `aCol` and `_partitiontime`, but the final dataframe does not. If you were to iterate over `row_iter` directly, you would also see values in this `_partitiontime` column.

**Comment by meredithslota** [comment] 2022-08-12 16:03
Thanks for the report — I wonder if the backend behavior changed in someway to allow this? Regardless, we definitely shouldn't be dropping columns like this. Tagged as P1 accordingly.

**Comment by mtagle** [comment] 2022-08-12 20:47
It's not impossible for me to use aliases, but my work would be much easier if I didn't have to alias it everywhere I was querying it

**Comment by shollyman** [comment] 2022-08-15 16:18
The alternative would necessitate providing the column list in some fashion, though it could be derived from the results (at the cost of needing to do this extra schema work).  It's not a "real" column but an artifact of the underlying storage configuration, and also has some type considerations (projecting _PARTITIONTIME vs _PARTITIONDATE, etc).

I'm going to mark this as a feature request for now.

**Comment by shollyman** [comment] 2022-08-19 20:40
Status:  After some out-of-band conversation with reporter, leaving this as feature request to see if we get additional feedback about this pattern.  It's an odd interaction flow and the reporter has a workaround, so updating priority.

Explicit projection of table columns is already supported when requesting a row iterator from a table (via the `selected_fields` kwarg).  It is unclear (pending updates on the internal issue 242325714) whether behavior of projecting the pseudocolumn name unaltered is the correct behavior; reporter also noted that previous behavior of projecting the pseudocolumn directly wasn't supported but seems to be at present.

**Comment by chalmerlowe** [comment] 2024-07-26 13:43
Closing. Customer has workaround and the system is functioning as designed.

**Closed by chalmerlowe** 2024-07-26 13:43 UTC
Labels: api: bigquery, type: feature request, priority: p3
