### ISSUE TITLE
Retry did not occurred

### ISSUE THREAD

**Issue by nitishxp** [googleapis/python-bigquery#707] opened 2021-06-15 17:19 UTC
Hi, 

I got the following error in one of my Cloud function
```
, in reraise raise self.last_attempt.result()
File "/opt/python3.8/lib/python3.8/concurrent/futures/_base.py", line 437, in result return self.__get_result()
File "/opt/python3.8/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result raise self._exception
File "/layers/google.python.pip/pip/lib/python3.8/site-packages/tenacity/__init__.py", line 426, in __call__ result = fn(*args, **kwargs)
File "/workspace/cf/functions.py", line 602, in execute_query return self.gbq.query(query).result()
File "/layers/google.python.pip/pip/lib/python3.8/site-packages/google/cloud/bigquery/job/query.py", line 1172, in result super(QueryJob, self).result(retry=retry, timeout=timeout)
File "/layers/google.python.pip/pip/lib/python3.8/site-packages/google/cloud/bigquery/job/base.py", line 679, in result return super(_AsyncJob, self).result(timeout=timeout, **kwargs)
File "/layers/google.python.pip/pip/lib/python3.8/site-packages/google/api_core/future/polling.py", line 134, in result raise
  self._exception google.api_core.exceptions.InternalServerError: 500 Job failed because streaming data from one of the tables referenced in the query is temporarily unavailable. Retrying the job may solve the problem
```

**Comment by tseaver** [comment] 2021-06-18 20:22
@plamut, @tswast PTAL.

**Comment by plamut** [comment] 2021-06-22 10:48
@nitishxp By default, `InternalServerError` is is listed among the [retriable errors](https://github.com/googleapis/python-bigquery/blob/18bb443c7acd0a75dcb57d9aebe38b2d734ff8c7/google/cloud/bigquery/retry.py#L25-L32). Ditto if the exception instance contains a reason sent by the backend, `"internalError"` is one of them.

Does the error occur often, or was it just a one-time event_

Is your code perhaps using a custom Retry object? (a sample would be great) And which package versions do you have installed? Is there anything else in the logs that might lead to the eventual error posted here?

Any additional info would be useful, thanks!

**Comment by nitishxp** [comment] 2021-06-25 10:01
@plamut It was a one time exception that occurred in Cloud Function.

Yes I am also using tenacity retry module.

Below are installed packages 

google-cloud-bigquery==2.15.0
google-auth==1.30.0
google-cloud-pubsub==2.2.0
google-cloud-scheduler==2.1.0
google-cloud-storage==1.38.0
google-cloud-kms==2.2.0
google-cloud-secret-manager==2.1.0
google-api-python-client==2.7.0

**Comment by tswast** [comment] 2021-06-28 21:19
From your stacktrace "500 Job failed because streaming data from one of the tables referenced in the query is temporarily unavailable. Retrying the job may solve the problem"

Retrying the API request won't help. You actually have to re-issue the query.

Closing as a duplicate of https://github.com/googleapis/python-bigquery/issues/539

**Closed by tswast** 2021-06-28 21:19 UTC
Labels: api: bigquery, type: question

**Comment by nitishxp** [comment] 2021-06-29 05:05
@tswast will the sdk take care of it in the future releases?
