### ISSUE TITLE
invalid literal for int() with base 10 when fetching fraction seconds in TIMESTAMP field

### ISSUE THREAD

**Issue by peku33** [googleapis/python-bigquery#436] opened 2020-12-14 15:05 UTC
This problem was introduced with `google-cloud-bigquery` version `2.6`.
When fetching TIMESTAMP field that contains fractional seconds, exception will be raised:

```
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _  
<snip>\bigquery\query.py:215: in __iter__
    return iter(self.rows)
venv_win\lib\site-packages\google\cloud\bigquery\query.py:590: in rows
    return _rows_from_json(self._properties.get("rows", ()), self.schema)
venv_win\lib\site-packages\google\cloud\bigquery\_helpers.py:267: in _rows_from_json
    return [Row(_row_tuple_from_json(r, schema), field_to_index) for r in values]
venv_win\lib\site-packages\google\cloud\bigquery\_helpers.py:267: in <listcomp>
    return [Row(_row_tuple_from_json(r, schema), field_to_index) for r in values]
venv_win\lib\site-packages\google\cloud\bigquery\_helpers.py:242: in _row_tuple_from_json
    row_data.append(_field_from_json(cell["v"], field))
venv_win\lib\site-packages\google\cloud\bigquery\_helpers.py:218: in _field_from_json
    return converter(resource, field)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _  

value = '1.577970977000018E9', field = SchemaField('hour', 'TIMESTAMP', 'NULLABLE', None, (), None)

    def _timestamp_from_json(value, field):
        """Coerce 'value' to a datetime, if set or not nullable."""
        if _not_null(value, field):
            # value will be a integer in seconds, to microsecond precision, in UTC.
>           return _datetime_from_microseconds(int(value))
E           ValueError: invalid literal for int() with base 10: '1.577970977000018E9'
```

Bug is here: https://github.com/googleapis/python-bigquery/blob/78fde4a92e61a89d0b490b93acc90fff9635d1bf/google/cloud/bigquery/_helpers.py#L85

To trigger this, simply execute query fetching timestamp field with fractional seconds.
In my scenario I inserted `datetime(2020, 1, 2, 15, 16, 17, 18, timezone(timedelta(hours=2)))`

**Comment by tswast** [comment] 2020-12-17 21:42
It appears to me like the `formatOptions.useInt64Timestamp` option is not being set (added in https://github.com/googleapis/python-bigquery/pull/402/files#diff-fc3199dcfb64ea8758d31d37f30dc25c4885b1c21b03812fbc0f1914f48763f3).

Perhaps there are some cases where we fetch rows that we missed?

**Comment by tswast** [comment] 2020-12-17 22:07
It's possible this feature (https://issuetracker.google.com/147629356) hasn't rolled out to all projects, but I would have hoped it had since the bug was closed in March.

**Comment by peku33** [comment] 2020-12-17 22:15
Is there any way to check that?

**Comment by tswast** [comment] 2020-12-17 22:24
I've got a code sample here that makes raw API requests. Would you mind returning the output (after redacting any sensitive information, of course)?

```python
import sys
import time

import google.auth
import google.auth.transport.requests


project_id = "my-project"
table_id = "my-project.my_dataset.my_table"

credentials, _ = google.auth.default(scopes=["https://www.googleapis.com/auth/cloud-platform"])
session = google.auth.transport.requests.AuthorizedSession(credentials)

# Run a query so that we can benchmark getQueryResults.
job_post_url = f"https://bigquery.googleapis.com/bigquery/v2/projects/{project_id}/jobs"
job_request = {
    "configuration": {
        "query": {
            "query": f"SELECT * FROM `{table_id}`",
            "useLegacySql": False,
        }
    }
}

start_query = time.time()
job_response = session.post(job_post_url, json=job_request).json()
job_id = job_response["jobReference"]["jobId"]
job_get_url = f"https://bigquery.googleapis.com/bigquery/v2/projects/{project_id}/jobs/{job_id}"
while job_response["status"]["state"].upper() != "DONE":
    time.sleep(1.0)
    job_response = session.get(job_get_url).json()
end_query = time.time()

print(f"finished query in {end_query-start_query} seconds")
if job_response["status"].get("errorResult"):
    print(job_response["status"]["errorResult"])
    sys.exit(1)

get_query_results_url = f"https://bigquery.googleapis.com/bigquery/v2/projects/{project_id}/queries/{job_id}"
extra_params = {
    "prettyPrint": True,
    "formatOptions.useInt64Timestamp": True,
}

response = session.get(get_query_results_url, params=extra_params)
num_bytes = len(response.content)
print(response.content)
```

**Comment by peku33** [comment] 2020-12-17 22:38
```
"v": "1608244591539125"
```

So it looks like useInt64Timestamp worked here.

**Closed** 2020-12-18 12:03 UTC
Labels: api: bigquery, priority: p1, type: bug

**Comment by tswast** [comment] 2020-12-21 14:28
@peku33 I'm glad the feature works for your project. I'm still a bit concerned about how you ended up in the original state you reported. A code sample to reproduce the issue would be most helpful.

**Comment by peku33** [comment] 2020-12-21 15:29
I found that library I was working with used some custom workaround around missing https://cloud.google.com/bigquery/docs/reference/rest/v2/jobs/query endpoint and didn't set `formatOptions.useInt64Timestamp` properly.
