### ISSUE TITLE
`types-protobuf` overshadows `google-cloud` packages 

### ISSUE THREAD

**Issue by John15321** [googleapis/python-bigquery#1423] opened 2022-11-24 14:33 UTC
#### Environment details

  - OS type and version: Issue present on all OSs
  - Python version: present on versions 3.8, 3.9, 3.10
  - pip version: on versions from 22 to 23
  - `google-cloud-bigquery` version: 3.3.6

#### Steps to reproduce

Hi
The issue here is that the `types-protobuf` pakcage overshadows anything that `google-cloud-*` tried to export (by that I mean any google api package like `google-cloud-bigquery` or `google-cloud-storage`) which results in IDEs, language servers and all types of linters and type checkers failing even tho the code runs succesfully.

The issue is very simple to reproduce, simply install a package like `google-cloud-bigquery` and try to use it in your code.

When you open your IDE it will look something like this:
![image](https://user-images.githubusercontent.com/56229312/203807642-c67cd163-05b4-49f2-956e-b5afde77503c.png)

Tools like `mypy` or `pylint` will also not have a problem with that.

However if you install the `types-protobuf` package, which will be installed if you install `types-all` (that package is frequently installed in order for mypy to have type resolution for as many things as possible)m you will start getting errors like this (no matter the IDE):
![image](https://user-images.githubusercontent.com/56229312/203807985-ca2942f9-5083-4ab4-b936-87e019b12e84.png)

Even tho the code will run succesfully.
I am not sure if this is the fault of the `types-protobuf` package or maybe the google packages export something in a bad manner. I am simply reporting this issue, I am making a twin report in `types-protobuf` repo (https://github.com/python/typeshed/issues/9267).

**Comment by meredithslota** [comment] 2023-04-29 00:16
Root cause was in the `typeshed` repo, and it's now fixed (see linked issue, fix is here: https://github.com/python/typeshed/pull/8360). I'm going to close this out but if you see this crop up again, please let us know! Thanks for filing!

**Closed by meredithslota** 2023-04-29 00:16 UTC
Labels: api: bigquery

**Comment by John15321** [comment] 2023-04-29 00:20
Great! Thanks 🙏
