### ISSUE TITLE
google.api_core.exceptions.RetryError

### ISSUE THREAD

**Issue by nitishxp** [googleapis/python-bigquery#945] opened 2021-09-04 05:07 UTC
Sdk Version: 

google-cloud-bigquery==2.23.1

` File "/workspace/main.py", line 882, in create_table table = self.gbq.create_table(table, exists_ok=True) File "/layers/google.python.pip/pip/lib/python3.9/site-packages/google/cloud/bigquery/client.py", line 722, in create_table api_response = self._call_api( File "/layers/google.python.pip/pip/lib/python3.9/site-packages/google/cloud/bigquery/client.py", line 747, in _call_api return call() File "/layers/google.python.pip/pip/lib/python3.9/site-packages/google/api_core/retry.py", line 286, in retry_wrapped_func return retry_target( File "/layers/google.python.pip/pip/lib/python3.9/site-packages/google/api_core/retry.py", line 204, in retry_target six.raise_from( File "<string>", line 3, in raise_from google.api_core.exceptions.RetryError: Deadline of 120.0s exceeded while calling functools.partial(functools.partial(<bound method JSONConnection.api_request of <google.cloud.bigquery._http.Connection object at 0x3e7a63fbb2b0>>, method='POST', path='/projects/xx/datasets/xx/tables', data={'tableReference': {'projectId': 'xx, 'datasetId': 'xx', 'tableId': 'xx'}, 'labels': {}, 'schema': {'fields': [{'name': 'partitionDate', 'type': 'DATE', 'mode': 'REQUIRED', 'policyTags': {'names': []}}]}}, timeout=None)), last exception: 503 POST https://bigquery.googleapis.com/bigquery/v2/projects/xx/datasets/xx/tables?prettyPrint=false: Error encountered during execution. Retrying may solve the problem.`

**Comment by plamut** [comment] 2021-09-06 10:35
@nitishxp What is the question here, can you please elaborate?

It appears that creating a table failed, because the server was unavailable for more than 120 seconds, which is the default retry deadline. It seems like expected behavior by the client library?

**Comment by nitishxp** [comment] 2021-09-06 11:54
Okay @plamut i got confused with the underline exception :)

**Comment by plamut** [comment] 2021-09-06 11:55
@nitishxp No worries, I'll close the issue then. :)

**Closed by plamut** 2021-09-06 11:55 UTC
Labels: api: bigquery, type: question
