### ISSUE TITLE
BigQuery: to_dataframe does not respect date fields

### ISSUE THREAD

**Issue by QuinRiva** [googleapis/python-bigquery#11] opened 2019-12-06 03:13 UTC
#### Environment details

1. google-cloud-bigquery: version 1.22
2. OS type and version: Centos 7
3. Python version: 3.6.9

#### Steps to reproduce

  1. Download a table from BigQuery to a pandas Dataframe

#### Code example

```python
df = bq_client.list_rows(table).to_dataframe()
df.types

contractId                       int64
contractTypeId                   int64
affiliateId                      int64
invoicePeriodId                  int64
startDate                       **object**
endDate                         **object**
contractName                    object
details                         object
updated            datetime64[ns, UTC]
created            datetime64[ns, UTC]
dtype: object
```
Timestamps seem to work fine, but **date** is just being treated as a string.

Table schema is defined as:
```python
'contract' : [
            bigquery.SchemaField("contractId", "INTEGER", mode="REQUIRED"),
            bigquery.SchemaField("contractTypeId", "INTEGER", mode="REQUIRED"),
            bigquery.SchemaField("affiliateId", "INTEGER", mode="REQUIRED"),
            bigquery.SchemaField("invoicePeriodId", "INTEGER", mode="REQUIRED"),
            bigquery.SchemaField("startDate", "DATE", mode="REQUIRED"),
            bigquery.SchemaField("endDate", "DATE", mode="NULLABLE"),
            bigquery.SchemaField("contractName", "STRING", mode="NULLABLE"),
            bigquery.SchemaField("details", "STRING", mode="NULLABLE"),
            bigquery.SchemaField("created", "TIMESTAMP", mode="REQUIRED"),
            bigquery.SchemaField("updated", "TIMESTAMP", mode="REQUIRED"),
        ]
```
This should have anything to do with pagination, because the _startDate_ field is required; also the table only has 20 records.

**Comment by HemangChothani** [comment] 2020-06-16 06:53
@emkornfield Another issue has filed by user https://github.com/googleapis/python-bigquery/issues/136 which is duplicate of this issue.

As per comment received from user on the [issue](https://github.com/googleapis/python-bigquery/issues/136#issuecomment-644141436),  Manually setting the dtype argument works but user wants that automated.

**Comment by emkornfield** [comment] 2020-06-19 04:07
@HemangChothani I think this might be fixed after https://github.com/googleapis/python-bigquery/commit/e75ff8297c65981545b097f75a17cf9e78ac6772 (is this in the latest release?).  Otherwise I think it is possible this might be going through a different code path and not using pyarrow through the storage API (and not using arrow data so it still might be maintaining the string).  pyarrow will covert date types to datetime.date objects without intervention when using pa.record_batch.to_dataframe()

**Comment by HemangChothani** [comment] 2020-06-19 08:07
@emkornfield I have tried with the master branch as feature has not released, but still `to_dataframe` is the culprit. 

pyarrow works fine as `to_arrow` returns `date32` datatype`[pyarrow.RecordBatch dt: date32[day]]`
but line given below convert to df and return  df.dtype ['column'] = object https://github.com/googleapis/python-bigquery/blob/de9998fe85eea5e69be39cfe0075d3097ce9ec4a/google/cloud/bigquery/table.py#L1725

**Comment by emkornfield** [comment] 2020-06-19 16:21
@HemangChothani I expect it to be an object (but the object should be datetime.date).  If conversion to dtype=datetime64  is desired behavior I think you need to call [`record_batch.to_pandas(date_as_object=False)`](https://arrow.apache.org/docs/python/generated/pyarrow.RecordBatch.html#pyarrow.RecordBatch.to_pandas)

**Comment by HemangChothani** [comment] 2020-06-22 06:35
@emkornfield I have completely ignored that and expect it to be a `datetime64`, thanks for the clarification, is there any plan to expose this parameter for users, if not than can we close this issue as it's resolved?

**Comment by emkornfield** [comment] 2020-06-22 23:25
> is there any plan to expose this parameter for users, if not than can we close this issue as it's resolved?
The parameter is public in the pyarrow as far as I can tell.  It seems like at least some users of BQ expect date to become datetime64 I would therefor think it is a good idea to expose this as a parameter for BQ, but I don't know the exact policies that are followed.

**Closed** 2020-06-29 09:49 UTC
Labels: api: bigquery, status: awaiting information, type: question
