### ISSUE TITLE
ImportError: urllib3 v2.0 only supports OpenSSL 1.1.1+

### ISSUE THREAD

**Issue by asukan007** [googleapis/python-bigquery#1565] opened 2023-05-08 05:03 UTC
Seeing "ImportError: urllib3 v2.0 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with OpenSSL 1.0.2k-fips 26 Jan 2017. See: https://github.com/urllib3/urllib3/issues/2168" when I import this library. it pointed me to this issue, can someone help me with what's the fix for this?

**Comment by jcurlier** [comment] 2023-05-08 20:24
+1

**Comment by bejoinka** [comment] 2023-05-09 00:14
what version of python are you running? which computer? for example, the new apple silicon computers ship with a python ssl library that is compiled with libreSSL instead of openSSL, so you either need to build from source or install a version of python that is already compiled with the correct openSSL.

you'll see which version of openSSL is a dependency on homebrew, for example, with:
```zsh
$ brew deps --tree python
python@3.11
├── mpdecimal
├── openssl@1.1
│   └── ca-certificates
├── sqlite
│   └── readline
└── xz
```

👍

**Comment by RameshChandraTR** [comment] 2023-05-09 11:53
Seeing error as -> Unable to import module urllib3 v2.0 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with OpenSSL 1.0.2k-fips. When I import the module .It pointed me to this issue, can someone help me with what's the fix for this?

**Comment by wiedemannsimon** [comment] 2023-05-11 10:07
+1

**Comment by martinamunoz** [comment] 2023-05-11 23:59
If you are using Certbot you can set specific version of urllib like this with pip:
sudo pip install --upgrade urllib3==1.26.15
To avoid version problems. And with certbot can use this:
sudo /opt/certbot/bin/pip install --upgrade urllib3==1.26.15

**Comment by RameshChandraTR** [comment] 2023-05-12 09:24
@martinamunoz I am not using certbot with sudo , can you please suggest the other alternate way or version of urllib3 which working fine with python 3.9

**Comment by asukan007** [comment] 2023-05-14 23:09
I had attempted to specify the openssl version, but it didn't work.
Instead, I specified the version of urllib3==1.26.15 and it worked!

**Comment by huyenuet** [comment] 2023-05-17 06:42
@Akanksh29 you can use this command to install a specific version of urllib3
`pip install urllib3==1.26.6`
I had the same issue and Version 1.26.6 worked for me.

**Comment by Its-suLav-D** [comment] 2023-05-20 01:50
@huyenuet Which version of python were you using?

**Comment by asukan007** [comment] 2023-05-21 22:40
@Akanksh29 
> Where did you specify the urllib3 version in glue?

If your requirements allow you to obtain wheel files from PyPI, you can install and use urllib3 v1.26.15 by specifying the following job parameters in glue.

# job parameter
- Key: --additional-python-modules
- Value: google-cloud-bigquery==3.4.1 urllib3==1.26.15

**Comment by Onyekam** [comment] 2023-06-12 15:16
> I am using this liberaly in AWS Glue. I had attempted to specify the openssl version, but it didn't work. Instead, I specified the version of urllib3==1.26.15 and it worked!

Hi, I would like to know how you were able to specify this - I don't have the "--additional-python-modules" key option in the Glue Job Parameter Options

**Comment by Onyekam** [comment] 2023-06-12 15:55
> > I am using this liberaly in AWS Glue. I had attempted to specify the openssl version, but it didn't work. Instead, I specified the version of urllib3==1.26.15 and it worked!

Nevermind, I've resolved it. In my case I was using a version of requests library that was too recent. Downgrading to version 2.29 fixed the issue.

**Comment by chalmerlowe** [comment] 2023-06-20 13:33
OP determined the error. The error was not with our library. Closing.

**Closed by chalmerlowe** 2023-06-20 13:33 UTC
Labels: api: bigquery

**Comment by theandrelima** [comment] 2023-11-07 18:20
> @Akanksh29 you can use this command to install a specific version of urllib3 `pip install urllib3==1.26.6` I had the same issue and Version 1.26.6 worked for me.

this doesn't work for me on Amazon Linux 2 using python3.8 and python3.9 installed with pyenv

**Comment by amaljose01** [comment] 2024-06-14 06:34
The error message you're encountering indicates that urllib3 version 2 requires OpenSSL 1.1.1 or newer, but your Python environment is using LibreSSL 2.8.3. This incompatibility is causing the warnings and likely the subsequent failure.

You can resolve it by following below steps, I assume the device is MacOS

**Step 1: upgrade OpenSSL**

    ```
brew update
    brew upgrade openssl
    brew link --force openssl
```
**Step 2: Reinstall python with correct SSL**

   ```
 # Ensure pyenv is up-to-date
    brew update
    brew upgrade pyenv
    
    # Install Python with the correct OpenSSL
    env PYTHON_CONFIGURE_OPTS="--with-openssl=$(brew --prefix openssl)" pyenv install 3.9.x
    
    # Set the newly installed Python as the global version
    pyenv global 3.9.x
```

x is a place holder here, you can use like below

`    env PYTHON_CONFIGURE_OPTS="--with-openssl=$(brew --prefix openssl@1.1)" pyenv install 3.9.13
`

**Step 3: upgrade urllib3**

`    pip install --upgrade urllib3
**`Step 4: verify the installation**

`    python -c "import ssl; print(ssl.OPENSSL_VERSION)"
`

**Comment by ryvdx** [comment] 2024-06-24 14:47
Unless you have a specific reason for using a dependency already in the Glue runtime that is a different version, I suggest using the ones here.

(in my case and I assume many others above too, this error was caused by having "requests" in my requirements.txt at a version that is too new, building my source with a setup.py, and then importing that as a glue job reference.  Doing that, installed urllib3 as a child dependency at too new of a version that created that error above.)

https://docs.aws.amazon.com/glue/latest/dg/aws-glue-programming-python-libraries.html#glue-modules-provided

If you are like me, and like to build a WHL from the source and use separate entry points for AWS Glue and local dev that call your code, then use a requirements.txt and separate dev-requirements.txt to install dependencies already available in the glue runtime.
