### ISSUE TITLE
module 'proto' has no attribute 'module'

### ISSUE THREAD

**Issue by sabrikaragonen** [googleapis/python-bigquery#1368] opened 2022-09-27 10:31 UTC
#### Environment details

  -  OS type and version: `Ubuntu 20.04.3 LTS`
  -  Python version: `Python 3.8.5`
  -  pip version: `22.1.2`
  -  google-cloud-bigquery==`3.3.2`
  -  google-cloud-bigquery-storage==`2.16.0`
  -  proto-plus==`1.22.1`
  -  protobuf==`4.21.6`

#### Steps to reproduce

  1. Just importing bigquery package

#### Code example

```python
`from google.cloud import bigquery`
```

#### Stack trace
```
Cell In [2], line 1
----> 1 from google.cloud import bigquery

File ~/miniconda3/envs/sabri.karagonen/lib/python3.8/site-packages/google/cloud/bigquery/__init__.py:35
     31 from google.cloud.bigquery import version as bigquery_version
     33 __version__ = bigquery_version.__version__
---> 35 from google.cloud.bigquery.client import Client
     36 from google.cloud.bigquery.dataset import AccessEntry
     37 from google.cloud.bigquery.dataset import Dataset

File ~/miniconda3/envs/sabri.karagonen/lib/python3.8/site-packages/google/cloud/bigquery/client.py:59
     57 from google.cloud import exceptions  # pytype: disable=import-error
     58 from google.cloud.client import ClientWithProject  # type: ignore  # pytype: disable=import-error
---> 59 from google.cloud.bigquery_storage_v1.services.big_query_read.client import (
     60     DEFAULT_CLIENT_INFO as DEFAULT_BQSTORAGE_CLIENT_INFO,
     61 )
     63 from google.cloud.bigquery import _job_helpers
     64 from google.cloud.bigquery._job_helpers import make_job_id as _make_job_id

File ~/miniconda3/envs/sabri.karagonen/lib/python3.8/site-packages/google/cloud/bigquery_storage_v1/services/big_query_read/__init__.py:16
      1 # -*- coding: utf-8 -*-
      2 # Copyright 2022 Google LLC
      3 #
   (...)
     14 # limitations under the License.
     15 #
---> 16 from .client import BigQueryReadClient
     17 from .async_client import BigQueryReadAsyncClient
     19 __all__ = (
     20     "BigQueryReadClient",
     21     "BigQueryReadAsyncClient",
     22 )

File ~/miniconda3/envs/sabri.karagonen/lib/python3.8/site-packages/google/cloud/bigquery_storage_v1/services/big_query_read/client.py:37
     34 except AttributeError:  # pragma: NO COVER
     35     OptionalRetry = Union[retries.Retry, object]  # type: ignore
---> 37 from google.cloud.bigquery_storage_v1.types import arrow
     38 from google.cloud.bigquery_storage_v1.types import avro
     39 from google.cloud.bigquery_storage_v1.types import storage

File ~/miniconda3/envs/sabri.karagonen/lib/python3.8/site-packages/google/cloud/bigquery_storage_v1/__init__.py:25
     19 import pkg_resources
     21 __version__ = pkg_resources.get_distribution(
     22     "google-cloud-bigquery-storage"
     23 ).version  # noqa
---> 25 from google.cloud.bigquery_storage_v1 import client
     26 from google.cloud.bigquery_storage_v1 import types
     29 class BigQueryReadClient(client.BigQueryReadClient):

File ~/miniconda3/envs/sabri.karagonen/lib/python3.8/site-packages/google/cloud/bigquery_storage_v1/client.py:28
     26 from google.cloud.bigquery_storage_v1 import reader
     27 from google.cloud.bigquery_storage_v1.services import big_query_read
---> 28 from google.cloud.bigquery_storage_v1.services import big_query_write
     31 _SCOPES = (
     32     "https://www.googleapis.com/auth/bigquery",
     33     "https://www.googleapis.com/auth/cloud-platform",
     34 )
     37 class BigQueryReadClient(big_query_read.BigQueryReadClient):

File ~/miniconda3/envs/sabri.karagonen/lib/python3.8/site-packages/google/cloud/bigquery_storage_v1/services/big_query_write/__init__.py:16
      1 # -*- coding: utf-8 -*-
      2 # Copyright 2022 Google LLC
      3 #
   (...)
     14 # limitations under the License.
     15 #
---> 16 from .client import BigQueryWriteClient
     17 from .async_client import BigQueryWriteAsyncClient
     19 __all__ = (
     20     "BigQueryWriteClient",
     21     "BigQueryWriteAsyncClient",
     22 )

File ~/miniconda3/envs/sabri.karagonen/lib/python3.8/site-packages/google/cloud/bigquery_storage_v1/services/big_query_write/client.py:47
     44 except AttributeError:  # pragma: NO COVER
     45     OptionalRetry = Union[retries.Retry, object]  # type: ignore
---> 47 from google.cloud.bigquery_storage_v1.types import storage
     48 from google.cloud.bigquery_storage_v1.types import stream
     49 from google.cloud.bigquery_storage_v1.types import table

File ~/miniconda3/envs/sabri.karagonen/lib/python3.8/site-packages/google/cloud/bigquery_storage_v1/types/__init__.py:16
      1 # -*- coding: utf-8 -*-
      2 # Copyright 2022 Google LLC
      3 #
   (...)
     14 # limitations under the License.
     15 #
---> 16 from .arrow import (
     17     ArrowRecordBatch,
     18     ArrowSchema,
     19     ArrowSerializationOptions,
     20 )
     21 from .avro import (
     22     AvroRows,
     23     AvroSchema,
     24     AvroSerializationOptions,
     25 )
     26 from .protobuf import (
     27     ProtoRows,
     28     ProtoSchema,
     29 )

File ~/miniconda3/envs/sabri.karagonen/lib/python3.8/site-packages/google/cloud/bigquery_storage_v1/types/arrow.py:19
      1 # -*- coding: utf-8 -*-
      2 # Copyright 2022 Google LLC
      3 #
   (...)
     14 # limitations under the License.
     15 #
     16 import proto  # type: ignore
---> 19 __protobuf__ = proto.module(
     20     package="google.cloud.bigquery.storage.v1",
     21     manifest={
     22         "ArrowSchema",
     23         "ArrowRecordBatch",
     24         "ArrowSerializationOptions",
     25     },
     26 )
     29 class ArrowSchema(proto.Message):
     30     r"""Arrow schema as specified in
     31     https://arrow.apache.org/docs/python/api/datatypes.html and
     32     serialized to bytes using IPC:
   (...)
     38             IPC serialized Arrow schema.
     39     """

AttributeError: module 'proto' has no attribute 'module'
```

Making sure to follow these steps will guarantee the quickest resolution possible.

Thanks!

**Comment by Raz-Hemo** [comment] 2022-10-03 14:20
I'm getting this as well.

**Comment by Eyald6** [comment] 2022-10-26 08:49
Make sure you don't hijack the module (`proto` directory with `__init__.py` in it or `proto.py` in your path).
To verify - manually `import proto` then `print(proto)` to check the module path.

If you're using `bazel` you might have a directory with the name `proto` that an `__init__.py` file is automatically created inside of it by `bazel` due to legacy reasons. Try using `legacy_create_init = 0,` in your `py_binary` / `py_test` / ...

**Comment by chalmerlowe** [comment] 2023-04-04 15:29
Closing as not reproducible.

**Closed by chalmerlowe** 2023-04-04 15:29 UTC
Labels: api: bigquery, status: will not fix
