### ISSUE TITLE
load_table_from_json interpolates string as int

### ISSUE THREAD

**Issue by ben-marengo-msmg** [googleapis/python-bigquery#1228] opened 2022-04-22 12:52 UTC
#### Issue

using `load_table_from_json()` to load data into a string column fails when using a value that can be interpolated as an int (eg. "123")

see code snippet, which shows inconsistency with the other data loading apis

#### Environment details

  - OS type and version: macos 12.2.1
  - Python version: 3.9.5 (also errors on 3.8)
  - pip version: `pip --version`
  - `google-cloud-bigquery` version: 2.31.0 & 3.0.1

#### Code example

```python
import io
import json

from google.api_core.exceptions import BadRequest
from google.cloud.bigquery import Client, Table, SchemaField

data = [{"col_1": "123"}]

project = 'my-project'
bq = Client(project)

table = Table(f'{project}.aaa.data_load_test', schema=[SchemaField("col_1", "STRING"), ])
bq.delete_table(table, not_found_ok=True)
bq.create_table(table)


# WORKS: bq load from byte stream
with io.StringIO() as fp:
    json.dump(data, fp)
    fp.seek(0)
    bq.load_table_from_file(fp, table).result()


# WORKS: streaming api
bq.insert_rows_json(table, data)


try:
    # FAILS: bq load from python dict.
    # 123 is interpolated as an int, even though i supply it as a string
    bq.load_table_from_json(data, table).result()
except BadRequest as e:
    print("ERROR")
    print(e)


# WORKS: bq load from python dict, but 123d cannot be interpolated as an int
bq.load_table_from_json([{"col_1": "123d"}], table).result()

```

#### Stack trace

```
Traceback (most recent call last):
  File "/Users/ben.marengo/code/scratch/bq_load.py", line 28, in <module>
    bq.load_table_from_json(data, table).result()
  File "/Users/ben.marengo/code/pyenvs/scratch/lib/python3.9/site-packages/google/cloud/bigquery/job/base.py", line 728, in result
    return super(_AsyncJob, self).result(timeout=timeout, **kwargs)
  File "/Users/ben.marengo/code/pyenvs/scratch/lib/python3.9/site-packages/google/api_core/future/polling.py", line 137, in result
    raise self._exception
google.api_core.exceptions.BadRequest: 400 Provided Schema does not match Table my-project:aaa.data_load_test. Field col_1 has changed type from STRING to INTEGER
```

**Comment by tswast** [comment] 2022-05-02 20:23
This is a tough one. One possibility would be to omit any local schema interpolation (if there is any, I forget) and use an autodetect schema, instead.

I suspect you should be able to work around this issue by manually supplying the correct schema in a job configuration object.

**Comment by tswast** [comment] 2022-05-06 20:46
New theory: I see we don't have any client-side schema generation. Instead, the client adds `autodetect = True` if no schema is supplied.

https://github.com/googleapis/python-bigquery/blob/66500b4cc4d03873118cf40fc33615064842f06d/google/cloud/bigquery/client.py#L2760-L2761

Perhaps omitting this flag when the table already exists will help?

I suspect that the backend first attempts to generate a schema from the provided data and then compares that generated schema with the existing table. If this is the case, we should also file a backend issue (possibly in addition to adding a workaround in the client if the table already exists).

**Comment by miguel-graindata** [comment] 2023-05-08 12:19
I have been coming across the same issue when trying to load json files into BigQuery.  I thought the problem was already fixed (https://github.com/googleapis/python-bigquery/pull/1248) but the issue is still around.

How can we request that it is solved? This is the code that I am using to load data.

```
job_config = LoadJobConfig(create_disposition='CREATE_IF_NEEDED',
                                        write_disposition='WRITE_APPEND',
                                        autodetect=True)

bq_table = f'{project_id}.{dataset_id}.{table_id}'

job = bqclient.load_table_from_json(json_data, bq_table, job_config=job_config)
```

**Comment by meredithslota** [comment] 2023-06-05 19:14
#1248 was never merged, so perhaps that fix is still relevant. 

Re: https://github.com/googleapis/python-bigquery/issues/1228#issuecomment-1119996488 — if this turns out to be a backend issue we should absolutely file a bug with the correct team (and I'd propose not adding a client-side workaround since we'd have to undo it later and that might cause even more problems for folks).

**Comment by Linchin** [comment] 2024-01-25 00:58
I think this is less of a backend bug, since we are sending conflicting information to the backend: `autodetect` shouldn't be true when the table already exists. The problem is the client does not know if the table exists without making an API call to verify it. Adding this call may make the method take longer, but will reduce user confusion and time spent on errors like this. We may also update the documentation to ask people to make sure local schema aligns with existing table. WDYT? @tswast

**Comment by tswast** [comment] 2024-01-25 16:09
> Adding this call may make the method take longer, but will reduce user confusion and time spent on errors like this.

We already do this in some other methods, such as `list_rows`:

https://github.com/googleapis/python-bigquery/blob/39f33b210ecbe9c2fd390825d29393c2d80257f5/google/cloud/bigquery/client.py#L3928-L3932

Note: We should only do this call to `get_table` if all of the following is true:

* The job config specifies "APPEND" mode (or is not set, as this is the default, I believe)
* The job config does not have a schema or autodetect manually set already.

**Comment by Linchin** [comment] 2024-01-25 18:23
Awesome, I'll go fix this issue.

**Comment by Linchin** [comment] 2024-01-25 20:26
Truth table

| Schema Provided | (user) Autodetect | writeDisposition | Check Table Existence | (client) Autodetect |
| ----------- | ----------- | ----------- | ----------- | ----------- |
| T | T/F/not provided | * | F | same as user value |
| F   | T/F | * | F | same as user value | 
| F   | not provided | WRITE_APPEND / not provided | T | F if table exists, otherwise empty |
| F   | not provided | WRITE_TRUNCATE / WRITE_EMPTY | F | empty |

**Comment by Linchin** [comment] 2024-01-25 21:17
After playing around, I'm starting to feel like we just don't have to set `autodetect = True` in the first place. For example, when I use `load_table_from_json` with schema and autodetect not set, the backend is still able to detect the schema. As these two lines of code were added five years ago, I guess maybe we had to do it in the past, but the backend has updated since? @tswast I wanted to double check the reason why we added it in the past.

**Comment by tswast** [comment] 2024-01-25 22:51
If a table doesn't already exist, it used to be the case that either you had to specify a `schema` or you had to specify `autodetect = True`. With neither specified, it would error. It could be that now BigQuery automatically autodetects the schema in this case?

**Comment by tswast** [comment] 2024-01-25 22:51
If the table does exist, you don't have to set anything.

**Comment by Linchin** [comment] 2024-01-25 23:03
> It could be that now BigQuery automatically autodetects the schema in this case?

I think so. I'll just remove these two lines then.

**Closed** 2024-01-30 18:02 UTC
Labels: api: bigquery, type: bug, priority: p2
